import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'PortFolio',
  description: 'Generated by create next app',
  icons: '',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body className="bg-fore dark:bg-back">{children}</body>
    </html>
  );
}
